name = "ctca4py"
version = "1.3.1"
license = "LICENSE"
author = "Takeshi NANRI"
maintainer = ""
copyright = "Takeshi NANRI"

[build]
auto-executables = false
auto-tests = true
auto-examples = true
external-modules = ["mpi"]

[library]
type = "shared"
